# Generated by Django 2.2.9 on 2020-01-28 01:39

from django.db import migrations, models
import djongo.models.fields
import twit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('text', models.TextField()),
                ('coordinates', djongo.models.fields.ListField()),
                ('hashtags', djongo.models.fields.ListField()),
                ('user', djongo.models.fields.EmbeddedField(model_container=twit.models.TwitUser, model_form_class=twit.models.TwitUserForm, null=True)),
            ],
        ),
    ]
