"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

# django
from django.core.exceptions import ImproperlyConfigured

# Other
from dotenv import load_dotenv
import os

# Directories
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
PACKAGE_ROOT = os.path.abspath(os.path.dirname(__file__))
RESOURCES_DIR = os.path.join(ROOT_DIR, 'resources')
RUNTIME_DIR = os.path.join(ROOT_DIR, 'run')
DJANGO_DIR = os.path.join(ROOT_DIR, 'src/app')
TEST_DIR = os.path.join(ROOT_DIR, 'tests')
# DOTENV_PATH = os.path.join(ROOT_DIR, "dev.env")


STATIC_DIR = os.path.join(RUNTIME_DIR, 'static')
STORAGE_DIR = os.path.join(RESOURCES_DIR, 'storage')
NFS_DIR = os.path.join(STORAGE_DIR, 'nfs/django')
LOGGING_DIR = os.path.join(RESOURCES_DIR, 'logs')

# testing suite.
os.sys.path.append(DJANGO_DIR)
os.sys.path.append(TEST_DIR)

# if not os.path.exists(DOTENV_PATH):
#     raise ImproperlyConfigured(
#         "DOTENV_PATH (%s) does not exist, but is required for setting up environment" % DOTENV_PATH
#     )
# else:
#     load_dotenv(DOTENV_PATH, verbose=True)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'true') == 'true'

ALLOWED_HOSTS = ['*']

ENVIRONMENT = os.getenv('ENVIRONMENT', 'development').lower()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')

if SECRET_KEY is '':
    raise ImproperlyConfigured(
        "SECRET_KEY does not exist, but is required for setting up environment"
    )

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    # apps
    'twit.apps.TwitConfig'

]

# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(DJANGO_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', ''),
        'USER': os.getenv('POSTGRES_USER', ''),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', ''),
        'PORT': os.getenv('POSTGRES_PORT', 5432)

    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = STATIC_DIR

MEDIA_ROOT = os.path.join(PACKAGE_ROOT, "media")
MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = ''
